refactor: remove redudant code and simplify lsp install & update (#10)
* refactor: remove redudant code and simplify lsp install & update

* chore: add find-process dependency

* refactor: remove redundant conditions and carry over junk from old code

* chore: add PR pipeline

* chore: fix matrix.node-version

* chore: remove cache: yarn entry due to 400 errors

example run:
```
/home/runner/.cache/yarn/v6
Error: Cache service responded with 400
```
https://github.com/ianandhum/vscode-protobuf-support/actions/runs/21545724900/job/62086783100?pr=10

* chore: improve extension.ts update order

* chore: remove duplicate infomessages during lsp update

* chore: update check is now more resiliant

* chore: newline at the end