chore: remove cache: yarn entry due to 400 errors
example run:
```
/home/runner/.cache/yarn/v6
Error: Cache service responded with 400
```
https://github.com/ianandhum/vscode-protobuf-support/actions/runs/21545724900/job/62086783100?pr=10